### PR TITLE
LP-5040 AMI Deploy 2.0 Dashboard Optimization

### PR DESCRIPTION
**Pull request by KR00713038**
- What does this PR do?
This AMI dashboard displays the deployment details of each components of all the environments.
- Are there critical parts that deserve extra attention?
No
- Where should the reviewer start?
From App and Web.config file
- How should this be manually tested; or how was it tested?
Manual
- Any background context or additional details you want to provide?
No
- Is there any change included on this PR that does not belong to the JIRA ticket?
No
- Screenshots (if appropriate)

Verify that the PR complies with all these checks:
- [ ] Updated documentation (if required)
- [x] Changes maintain the indentation of original files.
- [x] PR title follows the format "LP-XXXX: \<Ticket Title\>" | "LP-XXXX: \<general purpose of the PR\>"
- [ ] PR title is prefixed with "[WIP]" since it is not ready for review.
- [ ] Relevant changes are commented inline for simpler understanding (specially for long PRs)
- [ ] Checked with the accessibilityTester and gulp accessibilityTest task for new issues.
- [ ] New code is on par with latest ECMA features ([Examples of ECMA6]
- [ ] Consider using the vars.scss for reusable style values.

### CODE REVIEW

**Comment by ML00709559** [comment]
1. In DashboardController.cs - Hardcoding of ip address need to be avoided in the below mentioned function. Instead configure it in the web.config file.

 public ActionResult Getbuildlog(string env, string component, string version)
        {
            string env1 = Request.QueryString["env"];
            string component1 = Request.QueryString["component"];
            string version1 = Request.QueryString["version"];
            return Redirect("http://10.10.12.185:8080/job/test-build/8/");
        }

2. In GeneralModels.cs - inital value assigning should be changed to string.Empty rather than double quotes which is more efficient.

public string PROD { get; set; } = "";

3. Try to add more log statements to the method internally. Currently only in the begining the log statements are used. Adding more log statements will help us during troubleshooting.

**Comment by ML00709559** [comment]
Approved

**Review by ML00709559 — APPROVED** [review]
Approved

**Review by surendrakushwahacontractor — APPROVED** [review]

**Comment by RaghavendranR** [comment]
@KR00713038 : 
1. TOC API status end points wont work since we have no machine in which its deployed.  What alternative do we have to show it. Kindly check and let me know.
2. Do update the PR template for reference.

**Comment by RaghavendranR** [comment]
@KR00713038 : 
Approved. I cannot merge since there are no write access.

**Pull request merged**
